name: "OpenAPI-mock"
host: "openapi-mock.shanghai.cosmoplat.com"
port: "8080"
openApi:
  host: ""
rabbitMQ:
  host: "rabbitmq.shanghai.cosmoplat.com"
  port: "80"
  username: "addmnn"
  password: "Edn@ESR-3+"
  use: true